import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:utecbuild6/services/calculations.dart';

import 'map_page.dart';



class testing extends StatefulWidget {
  var currentPostion;

  testing({super.key, required this.currentPostion});

  @override
  State<testing> createState() => testingState();

}
class testingState extends State<testing> {



  List<Position> corners = [];
  double bearingThreshold = 45.0;
  double areaSqFt = 0.0;
  DistanceCalculation distanceCalculation = DistanceCalculation();

  @override
  Widget build(BuildContext context) {
    List<Position?> coordinates =
    [
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.1178704684915,longitude: 72.86452163735645),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.117806516605537,longitude: 72.86448416306904),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.117820975388508,longitude: 72.8644584306263),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.117840128037255,longitude: 72.86443973898223),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.117858861590843,longitude: 72.8644306865268),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.117878978158455,longitude: 72.86442364572814),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.117890629003863,longitude: 72.86440864212146),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11789976527832,longitude: 72.86439062102964),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.117902961790733,longitude: 72.86436810697452),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.117902525122826,longitude: 72.86434638169402),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11789869246125,longitude: 72.86432284417863),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11789461288589,longitude: 72.86429701789459),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11789479347534,longitude: 72.86427446139548),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.117893926853935,longitude: 72.86424924611757),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11789201852435,longitude: 72.86422375517786),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.117893061014865,longitude: 72.86419766971208),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11788911156839,longitude: 72.86417532883773),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11783354105738,longitude: 72.86414156916408),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.117843130600885,longitude: 72.8641188809357),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.1178419949928,longitude: 72.86409643232061),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.117826572405466,longitude: 72.86407087919139),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11781806861515,longitude: 72.86404947768492),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.117831642437288,longitude: 72.86403386654968),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.117830769132727,longitude: 72.86400585057739),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.117828591143407,longitude: 72.86397465249598),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11782695121626,longitude: 72.86394213874543),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.1178240407337,longitude: 72.8639144729114),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.117833910106352,longitude: 72.86388484033392),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11784587651269,longitude: 72.86386376613339),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.117833047887093,longitude: 72.86383894691457),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11783573397591,longitude: 72.86381139725913),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.117832635487506,longitude: 72.86378554093287),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.117848942917785,longitude: 72.86376598693803),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11785148280937,longitude: 72.86373811175767),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.117845088513732,longitude: 72.86371052452711),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.117851727751304,longitude: 72.86367862637137),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.117854821238293,longitude: 72.86365971398764),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11785208309681,longitude: 72.86363620842494),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.117849585152314,longitude: 72.86360426194507),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.117855293598026,longitude: 72.86358467015268),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.117855634378174,longitude: 72.86355458945945),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.117854162395492,longitude: 72.86352852920874),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11785183446111,longitude: 72.86349723609557),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.117859326770205,longitude: 72.86347109340981),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11787536591433,longitude: 72.86344742374114),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.117884824252524,longitude: 72.86342617297711),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11789295395752,longitude: 72.86340168713612),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11790093056574,longitude: 72.86337501173348),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11791960083088,longitude: 72.86336051569282),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11793975128073,longitude: 72.86335897167808),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11797243746182,longitude: 72.8633639982259),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.118000719450205,longitude: 72.86336822800534),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.1180247674006,longitude: 72.86337056395801),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.118050475468795,longitude: 72.86337281863865),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11807386041434,longitude: 72.8633734337954),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.118100109406086,longitude: 72.86337379839439),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.118124727687924,longitude: 72.86337461690947),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11814710182159,longitude: 72.86337430170698),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11817098193002,longitude: 72.86337643799303),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.118193177836833,longitude: 72.86337315210726),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11821835277138,longitude: 72.86338198505085),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11823640855387,longitude: 72.8633905078409),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.118256330643604,longitude: 72.86339999237411),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.118279212286332,longitude: 72.8634101959797),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.118303230823262,longitude: 72.86340459622039),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.118321406409283,longitude: 72.86340540586444),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.118355948284176,longitude: 72.86340823829046),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.118374188300926,longitude: 72.86340901705458),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.118399084167375,longitude: 72.86341919263074),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.118427486167068,longitude: 72.86341873998686),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.118447450023396,longitude: 72.86342478730359),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.118473415078387,longitude: 72.8634279194467),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.118491142213244,longitude: 72.86343341189391),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11851674754134,longitude: 72.86344468427583),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11854259747066,longitude: 72.86345550741413),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11856418051529,longitude: 72.86346334920968),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11859018215901,longitude: 72.86347003543307),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.118611305622622,longitude: 72.8634709782067),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.118637201711955,longitude: 72.86347466582978),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.118659798413667,longitude: 72.86348367272527),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11868635074131,longitude: 72.86348688356107),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11871339064383,longitude: 72.86350187132277),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11873087653281,longitude: 72.86350886951632),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.118761395329237,longitude: 72.86352176306193),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11877924075448,longitude: 72.86352564033186),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.118807457215233,longitude: 72.86351614382082),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.118831012027332,longitude: 72.8635263382065),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11885430310707,longitude: 72.86353620208507),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.118882085150307,longitude: 72.86354971502934),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.118907195519125,longitude: 72.86355480050783),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.118935263255537,longitude: 72.86356290503299),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.118950715187278,longitude: 72.8635830872464),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11894470816512,longitude: 72.86360143768106),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.118941206189465,longitude: 72.86362191369017),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.118932141835902,longitude: 72.86364858752918),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.118934327798186,longitude: 72.86366849527202),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11894217099839,longitude: 72.86369793647903),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.118950223067078,longitude: 72.86372071628944),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.118961389073878,longitude: 72.86374493194941),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11898149595835,longitude: 72.86377070802413),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.118991930801908,longitude: 72.86380053279117),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11900464807911,longitude: 72.86382389444644),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.119010176802398,longitude: 72.86385136230174),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11900655756251,longitude: 72.86387377447903),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.1190013528013,longitude: 72.86389940199255),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.119003936123573,longitude: 72.86392220691194),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.119010680422086,longitude: 72.86394949082252),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.119009792320778,longitude: 72.86397316110548),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11902776783143,longitude: 72.86399581249098),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.119041435670937,longitude: 72.86402486591435),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11906128402923,longitude: 72.86404869743357),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.119063439306082,longitude: 72.86407384246863),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11906280635874,longitude: 72.86410330561176),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.119068555335225,longitude: 72.86413179750686),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.119056971010973,longitude: 72.86414867031688),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.119060026758525,longitude: 72.86418029112664),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.119041520501263,longitude: 72.86420196385214),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.119036970066997,longitude: 72.86422710271188),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.119033926822596,longitude: 72.86424951593806),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.119033375624905,longitude: 72.8642774066933),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.119036807490236,longitude: 72.86430269259982),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.119048042857038,longitude: 72.86432916240376),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11903649465043,longitude: 72.86435137843273),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.119007696637258,longitude: 72.86437159755704),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.118994479638804,longitude: 72.86439823973411),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.118984924033125,longitude: 72.8644310032132),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.118981432261055,longitude: 72.86445663562485),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11897160802367,longitude: 72.86448486085624),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.118960936537203,longitude: 72.86451253241609),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.118927694535195,longitude: 72.86451394914744),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11890007557375,longitude: 72.86451117192233),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.11887379257553,longitude: 72.86451264532535),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.118849998432733,longitude: 72.86450543543135),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.118825443844514,longitude: 72.86450869868735),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.118801324808288,longitude: 72.86451265635489),
      Position(timestamp: widget.currentPostion.timestamp, accuracy: widget.currentPostion.accuracy, altitude: widget.currentPostion.altitude, altitudeAccuracy: widget.currentPostion.altitudeAccuracy, heading: widget.currentPostion.heading, headingAccuracy: widget.currentPostion.headingAccuracy, speed: widget.currentPostion.speed, speedAccuracy: widget.currentPostion.speedAccuracy,latitude: 19.118775113056408,longitude: 72.86451005674175)
    ];
    return Scaffold(
      body: Container(
        decoration: const BoxDecoration(
            gradient: RadialGradient(
                center: Alignment.topLeft,
                radius: 1.5,
                colors: [
                  Color(0xFFF2F1EE),
                  Color(0xFFE4E2DC)
                ]
            )
        ),

        child: SizedBox.expand(
          child: Center(
            child: SingleChildScrollView(
              child: Column(
                children: [
                  const Align(
                    alignment: Alignment.topCenter,
                    child: SafeArea(
                      child: Padding(
                        padding: EdgeInsets.only(top: 20),
                        child: Text(
                            "Welcome to Area Calculator smoothed coords!",
                            style: TextStyle(fontSize: 22), textAlign: TextAlign
                            .center),
                      ),
                    ),
                  ),
                  const SizedBox(
                    child: Padding(
                      padding: EdgeInsets.only(top: 20),
                      child: Text(
                        "After clicking Start Tracking, go around the Perimeter of your plot.\n"
                            "\n"
                            "After going around and reaching back to the start, click on stop tracking, then find out the area and look at the points on the map!",
                        textAlign: TextAlign.center,),
                    ),
                  ),
                  const SizedBox(height: 20,),
                  ElevatedButton(onPressed: () {
                    cornerDetectionV2(coordinates);
                    if (corners.isNotEmpty) {
                      List<LatLng> coords = corners.map((
                          position) =>
                          LatLng(position.latitude, position.longitude))
                          .toList();

                      var centroid = distanceCalculation.calculateCentroid(coords);

                      Navigator.push(context, MaterialPageRoute(
                          builder: (context) =>
                              MapPage(
                                  mapPoints: coords,
                                  area: areaSqFt,
                                  centroid: centroid,
                                  sideLengths: const []
                              )));
                    }
                  }, child: Text("Corner Detection")),

                ],
              ),
            ),
          ),
        ),
      ),
    );
  }

  Future<void> cornerDetectionV2(List<Position?>coordinates) async {
    for (int i = 0; i < coordinates.length; i++) {
      int nextIndex = (i + 1) % coordinates.length;
      int nextToNextIndex = (i + 2) % coordinates.length;

       var currentCoordinate = coordinates[i];
       var nextCoordinate = coordinates[nextIndex];
       var afterNextCoordinate = coordinates[nextToNextIndex];

      double bearing1 = Geolocator.bearingBetween(
        currentCoordinate!.latitude,
        currentCoordinate.longitude,
        nextCoordinate!.latitude,
        nextCoordinate.longitude,
      );

      double bearing2 = Geolocator.bearingBetween(
        nextCoordinate.latitude,
        nextCoordinate.longitude,
        afterNextCoordinate!.latitude,
        afterNextCoordinate.longitude,
      );

      double bearingChange = (bearing2 - bearing1).abs();
      if (bearingChange > 180) {
        bearingChange = 360 - bearingChange;
      }

      print("b2 is $bearing2");
      print("b1 is $bearing1");
      print("bearing change is $bearingChange");

      if (bearingChange >= bearingThreshold) {
        corners.add(nextCoordinate);
      }
      print(corners.length);
    }
  }


}
